baseURL = 'https://softwarenotes.netlify.app/'
languageCode = 'en-us'
theme='PaperMod'

title = 'Notes on Code & Systems'

[params]
ShowShareButtons = true
ShareButtons = ["x", "linkedin"]

  [params.analytics]
    [params.analytics.plausible]
      domain = "softwarenotes.netlify.app"
      scriptURI = "https://plausible.io/js/pa-69Ch3NvOfSaJTOX_kLOve.js"
      hashedScript = true

# Home Info Mode
[params.homeInfoParams]
Title = "Hi there 👋"
Content = "Welcome to my blog where I write about backends, distributed systems, system design and software architecture."

# Social Icons
[[params.socialIcons]]
name = "github"
url = "https://github.com/zombieleet"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/fmt_sprintf"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/victory-osikwemhe"

[markup.goldmark.renderer]
unsafe = true
